In [1]:
import pandas as pd
import requests
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

## Add the values of the LEZ areas

In [2]:
df_values = pd.read_csv(r"..\main\mean_monthlyvalues.csv")
df_LEZ_area = pd.read_csv(r"..\main\Visualisation\LEZ_area.csv")

In [3]:
df_values.head()

,Year_Month,Province,Average NO2 Value,Average PM2.5 Value,Average PM10 Value
0,1990-01,Drenthe,1.324917,NaN,NaN
1,1990-01,Flevoland,1.764091,NaN,NaN
2,1990-01,Friesland,1.215124,NaN,NaN
3,1990-01,Gelderland,2.422852,NaN,NaN
4,1990-01,Groningen,1.215124,NaN,NaN

In [4]:
df_LEZ_area.head()

,Unnamed: 0,zone_name,start_date,end_date,area_km2,province
0,0,LEZ 's-Hertogenbosch,2020-01-01T00:00:00Z,2025-03-01T00:00:00Z,2.856116,North-Brabant
1,1,LEZ Delft,2020-01-01T00:00:00Z,2999-01-01T00:00:00Z,1.374783,Zuid-Holland
2,2,LEZ Haarlem,2020-01-01T00:00:00Z,2999-01-01T00:00:00Z,11.509328,Noord-Holland
3,3,LEZ Apeldoorn,2025-01-01T00:00:00Z,2026-12-31T23:00:00Z,1.929479,Gelderland
4,4,LEZ Den Haag,2020-01-01T00:00:00Z,2999-01-01T00:00:00Z,12.110339,Zuid-Holland

In [5]:
# Standardize the date information
df_values['Year_Month'] = pd.to_datetime(df_values['Year_Month'], format='%Y-%m')

# Convert start_date and end_date to datetime
df_LEZ_area['start_date'] = pd.to_datetime(df_LEZ_area['start_date'], errors='coerce')
df_LEZ_area['end_date'] = pd.to_datetime(df_LEZ_area['end_date'], errors='coerce')

# Normalize to month start to match Year_Month convention
df_LEZ_area['start_date'] = df_LEZ_area['start_date'].dt.to_period('M').dt.to_timestamp()
df_LEZ_area['end_date'] = df_LEZ_area['end_date'].dt.to_period('M').dt.to_timestamp()

df_LEZ_area['end_date'] = df_LEZ_area['end_date'].fillna(pd.Timestamp('2100-12-01'))

C:\Users\Utente\AppData\Local\Temp\ipykernel_27932\3364337627.py:9: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_LEZ_area['start_date'] = df_LEZ_area['start_date'].dt.to_period('M').dt.to_timestamp()
C:\Users\Utente\AppData\Local\Temp\ipykernel_27932\3364337627.py:10: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_LEZ_area['end_date'] = df_LEZ_area['end_date'].dt.to_period('M').dt.to_timestamp()

In [6]:
df_LEZ_area.head()

,Unnamed: 0,zone_name,start_date,end_date,area_km2,province
0,0,LEZ 's-Hertogenbosch,2020-01-01,2025-03-01,2.856116,North-Brabant
1,1,LEZ Delft,2020-01-01,2100-12-01,1.374783,Zuid-Holland
2,2,LEZ Haarlem,2020-01-01,2100-12-01,11.509328,Noord-Holland
3,3,LEZ Apeldoorn,2025-01-01,2026-12-01,1.929479,Gelderland
4,4,LEZ Den Haag,2020-01-01,2100-12-01,12.110339,Zuid-Holland

In [7]:
print(df_LEZ_area)

    Unnamed: 0                 zone_name start_date   end_date    area_km2  \
0            0      LEZ 's-Hertogenbosch 2020-01-01 2025-03-01    2.856116
1            1                 LEZ Delft 2020-01-01 2100-12-01    1.374783
2            2               LEZ Haarlem 2020-01-01 2100-12-01   11.509328
3            3             LEZ Apeldoorn 2025-01-01 2026-12-01    1.929479
4            4              LEZ Den Haag 2020-01-01 2100-12-01   12.110339
5            5                 LEZ Breda 2020-01-01 2100-12-01    2.863319
6            6               LEZ Tilburg 2020-01-01 2025-01-01   14.858716
7            7               LEZ Utrecht 2020-01-01 2100-12-01    5.308662
8            8                LEZ Leiden 2020-01-01 2100-12-01    3.085373
9            9              LEZ Rijswijk 2020-01-01 2100-12-01    2.463771
10          10         Milieuzone Arnhem 2020-12-01 2100-12-01    1.137788
11          11             LEZ Amsterdam 2020-11-01 2025-01-01  102.919258
12          12     Milieuzone Maastricht 2020-01-01 2100-12-01    0.032038
13          13  LEZ Rotterdam Maasvlakte 2020-01-01 2100-12-01   57.173153

         province
0   North-Brabant
1    Zuid-Holland
2   Noord-Holland
3      Gelderland
4    Zuid-Holland
5   North-Brabant
6   North-Brabant
7         Utrecht
8    Zuid-Holland
9    Zuid-Holland
10     Gelderland
11  Noord-Holland
12        Limburg
13   Zuid-Holland

In [8]:
print(df_LEZ_area['area_km2'].skew())

2.6056328717405917

In [9]:
df_LEZ_area['area_km2_log'] = np.log(df_LEZ_area['area_km2'])
print(df_LEZ_area['area_km2_log'])
print(df_LEZ_area['area_km2_log'].skew())

0     1.049463
1     0.318296
2     2.443158
3     0.657250
4     2.494060
5     1.051982
6     2.698587
7     1.669340
8     1.126673
9     0.901693
10    0.129086
11    4.633945
12   -3.440825
13    4.046084
Name: area_km2_log, dtype: float64
-0.76735308313608

In [10]:
# Standardize values for LEZ area
from sklearn.preprocessing import StandardScaler

standardization = df_LEZ_area[['area_km2_log']]

standardize = StandardScaler().fit_transform(standardization)

df_LEZ_area['area_km2_st'] = pd.DataFrame(standardize, columns=standardization.columns)

print(df_LEZ_area)

    Unnamed: 0                 zone_name start_date   end_date    area_km2  \
0            0      LEZ 's-Hertogenbosch 2020-01-01 2025-03-01    2.856116
1            1                 LEZ Delft 2020-01-01 2100-12-01    1.374783
2            2               LEZ Haarlem 2020-01-01 2100-12-01   11.509328
3            3             LEZ Apeldoorn 2025-01-01 2026-12-01    1.929479
4            4              LEZ Den Haag 2020-01-01 2100-12-01   12.110339
5            5                 LEZ Breda 2020-01-01 2100-12-01    2.863319
6            6               LEZ Tilburg 2020-01-01 2025-01-01   14.858716
7            7               LEZ Utrecht 2020-01-01 2100-12-01    5.308662
8            8                LEZ Leiden 2020-01-01 2100-12-01    3.085373
9            9              LEZ Rijswijk 2020-01-01 2100-12-01    2.463771
10          10         Milieuzone Arnhem 2020-12-01 2100-12-01    1.137788
11          11             LEZ Amsterdam 2020-11-01 2025-01-01  102.919258
12          12     Milieuzone Maastricht 2020-01-01 2100-12-01    0.032038
13          13  LEZ Rotterdam Maasvlakte 2020-01-01 2100-12-01   57.173153

         province  area_km2_log  area_km2_st
0   North-Brabant      1.049463    -0.194515
1    Zuid-Holland      0.318296    -0.585982
2   Noord-Holland      2.443158     0.551669
3      Gelderland      0.657250    -0.404506
4    Zuid-Holland      2.494060     0.578922
5   North-Brabant      1.051982    -0.193167
6   North-Brabant      2.698587     0.688426
7         Utrecht      1.669340     0.137367
8    Zuid-Holland      1.126673    -0.153177
9    Zuid-Holland      0.901693    -0.273631
10     Gelderland      0.129086    -0.687285
11  Noord-Holland      4.633945     1.724617
12        Limburg     -3.440825    -2.598616
13   Zuid-Holland      4.046084     1.409877

In [11]:
# Define the function that add the LEZ area
def get_area(row):
    province = row['Province']
    date = row['Year_Month']
    # Filter by province
    matches = df_LEZ_area[
        (df_LEZ_area['province'] == province) &
        (df_LEZ_area['start_date'] <= date) &
        (df_LEZ_area['end_date'] >= date)
    ]

    # Sum all matching areas (if multiple)
    area_sum = matches['area_km2_st'].sum() if not matches.empty else 0

    # Add to existing value if present, else just area_sum
    current_val = row['area_km2_st'] if pd.notna(row.get('area_km2_st', None)) else 0
    return current_val + area_sum

if 'area_km2_st' not in df_values.columns:
    df_values['area_km2_st'] = 0

df_values['area_km2_st'] = df_values.apply(get_area, axis=1)

In [12]:
display(df_values)

,Year_Month,Province,Average NO2 Value,Average PM2.5 Value,Average PM10 Value,area_km2_st
0,1990-01-01,Drenthe,1.324917,NaN,NaN,0.000000
1,1990-01-01,Flevoland,1.764091,NaN,NaN,0.000000
2,1990-01-01,Friesland,1.215124,NaN,NaN,0.000000
3,1990-01-01,Gelderland,2.422852,NaN,NaN,0.000000
4,1990-01-01,Groningen,1.215124,NaN,NaN,0.000000
...,...,...,...,...,...,...
1435,2024-12-01,Noord-Holland,0.336776,0.122001,-0.208369,2.276287
1436,2024-12-01,Overijssel,-0.870952,-0.956227,-1.362410,0.000000
1437,2024-12-01,Utrecht,-0.102398,0.391558,-0.669985,0.137367
1438,2024-12-01,Zeeland,-0.761158,NaN,-0.208369,0.000000
1439,2024-12-01,Zuid-Holland,0.336776,0.391558,0.022440,0.976009

## Add the values for vehicles

In [13]:
{
  "odata.metadata":"https://opendata.cbs.nl/ODataApi/OData/85235NED/$metadata","value":[
    {
      "name":"TableInfos","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/TableInfos"
    },{
      "name":"UntypedDataSet","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/UntypedDataSet"
    },{
      "name":"TypedDataSet","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/TypedDataSet"
    },{
      "name":"DataProperties","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/DataProperties"
    },{
      "name":"CategoryGroups","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/CategoryGroups"
    },{
      "name":"RegioS","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/RegioS"
    },{
      "name":"Perioden","url":"https://opendata.cbs.nl/ODataApi/odata/85235NED/Perioden"
    }
  ]
}

{'odata.metadata': 'https://opendata.cbs.nl/ODataApi/OData/85235NED/$metadata',
 'value': [{'name': 'TableInfos',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/TableInfos'},
  {'name': 'UntypedDataSet',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/UntypedDataSet'},
  {'name': 'TypedDataSet',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/TypedDataSet'},
  {'name': 'DataProperties',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/DataProperties'},
  {'name': 'CategoryGroups',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/CategoryGroups'},
  {'name': 'RegioS',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/RegioS'},
  {'name': 'Perioden',
   'url': 'https://opendata.cbs.nl/ODataApi/odata/85235NED/Perioden'}]}

In [14]:
url = "https://opendata.cbs.nl/ODataApi/odata/85235NED/TypedDataSet"
response= requests.get(url)
users= response.json()
print(users)

{'odata.metadata': 'https://opendata.cbs.nl/ODataApi/OData/85235NED/$metadata#Cbs.OData.WebAPI.TypedDataSet', 'value': [{'ID': 0, 'RegioS': 'NL01  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 11372065, 'TotaalMotorvoertuigen_2': 10199679, 'TotaalPersonenautoS_3': 8442982, 'PersonenautoSRelatief_4': 489, 'InBezitNatuurlijkePersonen_5': 7452085, 'InBezitNatuurlijkePersonenRelatief_6': 431, 'TotaalBedrijfsvoertuigen_7': 2283037, 'TotaalBedrijfsmotorvoertuigen_8': 1110651, 'TotaalAanhangwagensEnOpleggers_9': 1172386, 'TotaalBedrijfsmotorvoertuigen_10': 1110651, 'Bestelauto_11': 903005, 'VrachtautoExclTrekkerVoorOplegger_12': 61652, 'TrekkerVoorOplegger_13': 78788, 'SpeciaalVoertuig_14': 57693, 'Bus_15': 9513, 'TotaalAanhangwagensEnOpleggers_16': 1172386, 'Aanhangwagen_17': 1008412, 'Oplegger_18': 163974, 'TotaalMotorfietsen_19': 646046, 'MotorfietsenRelatief_20': 37}, {'ID': 1, 'RegioS': 'NL01  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 11567203, 'TotaalMotorvoertuigen_2': 10374721, 'TotaalPersonenautoS_3': 8584391, 'PersonenautoSRelatief_4': 493, 'InBezitNatuurlijkePersonen_5': 7548770, 'InBezitNatuurlijkePersonenRelatief_6': 434, 'TotaalBedrijfsvoertuigen_7': 2328425, 'TotaalBedrijfsmotorvoertuigen_8': 1135943, 'TotaalAanhangwagensEnOpleggers_9': 1192482, 'TotaalBedrijfsmotorvoertuigen_10': 1135943, 'Bestelauto_11': 927251, 'VrachtautoExclTrekkerVoorOplegger_12': 61746, 'TrekkerVoorOplegger_13': 80118, 'SpeciaalVoertuig_14': 57129, 'Bus_15': 9699, 'TotaalAanhangwagensEnOpleggers_16': 1192482, 'Aanhangwagen_17': 1023980, 'Oplegger_18': 168502, 'TotaalMotorfietsen_19': 654387, 'MotorfietsenRelatief_20': 38}, {'ID': 2, 'RegioS': 'NL01  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 11704406, 'TotaalMotorvoertuigen_2': 10504756, 'TotaalPersonenautoS_3': 8686419, 'PersonenautoSRelatief_4': 497, 'InBezitNatuurlijkePersonen_5': 7683236, 'InBezitNatuurlijkePersonenRelatief_6': 440, 'TotaalBedrijfsvoertuigen_7': 2351390, 'TotaalBedrijfsmotorvoertuigen_8': 1151740, 'TotaalAanhangwagensEnOpleggers_9': 1199650, 'TotaalBedrijfsmotorvoertuigen_10': 1151740, 'Bestelauto_11': 945433, 'VrachtautoExclTrekkerVoorOplegger_12': 60831, 'TrekkerVoorOplegger_13': 79932, 'SpeciaalVoertuig_14': 56494, 'Bus_15': 9050, 'TotaalAanhangwagensEnOpleggers_16': 1199650, 'Aanhangwagen_17': 1029636, 'Oplegger_18': 170014, 'TotaalMotorfietsen_19': 666597, 'MotorfietsenRelatief_20': 38}, {'ID': 3, 'RegioS': 'NL01  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 11917133, 'TotaalMotorvoertuigen_2': 10688353, 'TotaalPersonenautoS_3': 8827709, 'PersonenautoSRelatief_4': 502, 'InBezitNatuurlijkePersonen_5': 7803950, 'InBezitNatuurlijkePersonenRelatief_6': 444, 'TotaalBedrijfsvoertuigen_7': 2411637, 'TotaalBedrijfsmotorvoertuigen_8': 1182857, 'TotaalAanhangwagensEnOpleggers_9': 1228780, 'TotaalBedrijfsmotorvoertuigen_10': 1182857, 'Bestelauto_11': 974792, 'VrachtautoExclTrekkerVoorOplegger_12': 60867, 'TrekkerVoorOplegger_13': 82436, 'SpeciaalVoertuig_14': 56230, 'Bus_15': 8532, 'TotaalAanhangwagensEnOpleggers_16': 1228780, 'Aanhangwagen_17': 1051486, 'Oplegger_18': 177294, 'TotaalMotorfietsen_19': 677787, 'MotorfietsenRelatief_20': 39}, {'ID': 4, 'RegioS': 'NL01  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 12063981, 'TotaalMotorvoertuigen_2': 10808892, 'TotaalPersonenautoS_3': 8917107, 'PersonenautoSRelatief_4': 501, 'InBezitNatuurlijkePersonen_5': 7842473, 'InBezitNatuurlijkePersonenRelatief_6': 440, 'TotaalBedrijfsvoertuigen_7': 2456150, 'TotaalBedrijfsmotorvoertuigen_8': 1201061, 'TotaalAanhangwagensEnOpleggers_9': 1255089, 'TotaalBedrijfsmotorvoertuigen_10': 1201061, 'Bestelauto_11': 989841, 'VrachtautoExclTrekkerVoorOplegger_12': 60811, 'TrekkerVoorOplegger_13': 85679, 'SpeciaalVoertuig_14': 55974, 'Bus_15': 8756, 'TotaalAanhangwagensEnOpleggers_16': 1255089, 'Aanhangwagen_17': 1069827, 'Oplegger_18': 185262, 'TotaalMotorfietsen_19': 690724, 'MotorfietsenRelatief_20': 39}, {'ID': 5, 'RegioS': 'NL01  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 12255576, 'TotaalMotorvoertuigen_2': 10989401, 'TotaalPersonenautoS_3': 9067393, 'PersonenautoSRelatief_4': 505, 'InBezitNatuurlijkePersonen_5': 7946287, 'InBezitNatuurlijkePersonenRelatief_6': 443, 'TotaalBedrijfsvoertuigen_7': 2484868, 'TotaalBedrijfsmotorvoertuigen_8': 1218693, 'TotaalAanhangwagensEnOpleggers_9': 1266175, 'TotaalBedrijfsmotorvoertuigen_10': 1218693, 'Bestelauto_11': 1006477, 'VrachtautoExclTrekkerVoorOplegger_12': 61521, 'TrekkerVoorOplegger_13': 86457, 'SpeciaalVoertuig_14': 55563, 'Bus_15': 8675, 'TotaalAanhangwagensEnOpleggers_16': 1266175, 'Aanhangwagen_17': 1077996, 'Oplegger_18': 188179, 'TotaalMotorfietsen_19': 703315, 'MotorfietsenRelatief_20': 39}, {'ID': 6, 'RegioS': 'NL01  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 12519332, 'TotaalMotorvoertuigen_2': 11234293, 'TotaalPersonenautoS_3': 9247810, 'PersonenautoSRelatief_4': 513, 'InBezitNatuurlijkePersonen_5': 8112145, 'InBezitNatuurlijkePersonenRelatief_6': 450, 'TotaalBedrijfsvoertuigen_7': 2550931, 'TotaalBedrijfsmotorvoertuigen_8': 1265892, 'TotaalAanhangwagensEnOpleggers_9': 1285039, 'TotaalBedrijfsmotorvoertuigen_10': 1265892, 'Bestelauto_11': 1050688, 'VrachtautoExclTrekkerVoorOplegger_12': 63197, 'TrekkerVoorOplegger_13': 87837, 'SpeciaalVoertuig_14': 54937, 'Bus_15': 9233, 'TotaalAanhangwagensEnOpleggers_16': 1285039, 'Aanhangwagen_17': 1096141, 'Oplegger_18': 188898, 'TotaalMotorfietsen_19': 720591, 'MotorfietsenRelatief_20': 40}, {'ID': 7, 'RegioS': 'LD01  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 1235405, 'TotaalMotorvoertuigen_2': 1071110, 'TotaalPersonenautoS_3': 861974, 'PersonenautoSRelatief_4': 500, 'InBezitNatuurlijkePersonen_5': 807624, 'InBezitNatuurlijkePersonenRelatief_6': 469, 'TotaalBedrijfsvoertuigen_7': 292901, 'TotaalBedrijfsmotorvoertuigen_8': 128606, 'TotaalAanhangwagensEnOpleggers_9': 164295, 'TotaalBedrijfsmotorvoertuigen_10': 128606, 'Bestelauto_11': 105174, 'VrachtautoExclTrekkerVoorOplegger_12': 5998, 'TrekkerVoorOplegger_13': 7520, 'SpeciaalVoertuig_14': 8205, 'Bus_15': 1709, 'TotaalAanhangwagensEnOpleggers_16': 164295, 'Aanhangwagen_17': 153306, 'Oplegger_18': 10989, 'TotaalMotorfietsen_19': 80530, 'MotorfietsenRelatief_20': 47}, {'ID': 8, 'RegioS': 'LD01  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 1258055, 'TotaalMotorvoertuigen_2': 1090809, 'TotaalPersonenautoS_3': 877666, 'PersonenautoSRelatief_4': 507, 'InBezitNatuurlijkePersonen_5': 819862, 'InBezitNatuurlijkePersonenRelatief_6': 474, 'TotaalBedrijfsvoertuigen_7': 299030, 'TotaalBedrijfsmotorvoertuigen_8': 131784, 'TotaalAanhangwagensEnOpleggers_9': 167246, 'TotaalBedrijfsmotorvoertuigen_10': 131784, 'Bestelauto_11': 108085, 'VrachtautoExclTrekkerVoorOplegger_12': 6062, 'TrekkerVoorOplegger_13': 7640, 'SpeciaalVoertuig_14': 8170, 'Bus_15': 1827, 'TotaalAanhangwagensEnOpleggers_16': 167246, 'Aanhangwagen_17': 155921, 'Oplegger_18': 11325, 'TotaalMotorfietsen_19': 81359, 'MotorfietsenRelatief_20': 47}, {'ID': 9, 'RegioS': 'LD01  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 1279895, 'TotaalMotorvoertuigen_2': 1110551, 'TotaalPersonenautoS_3': 892790, 'PersonenautoSRelatief_4': 515, 'InBezitNatuurlijkePersonen_5': 834668, 'InBezitNatuurlijkePersonenRelatief_6': 482, 'TotaalBedrijfsvoertuigen_7': 304021, 'TotaalBedrijfsmotorvoertuigen_8': 134677, 'TotaalAanhangwagensEnOpleggers_9': 169344, 'TotaalBedrijfsmotorvoertuigen_10': 134677, 'Bestelauto_11': 111159, 'VrachtautoExclTrekkerVoorOplegger_12': 5961, 'TrekkerVoorOplegger_13': 7640, 'SpeciaalVoertuig_14': 8118, 'Bus_15': 1799, 'TotaalAanhangwagensEnOpleggers_16': 169344, 'Aanhangwagen_17': 157735, 'Oplegger_18': 11609, 'TotaalMotorfietsen_19': 83084, 'MotorfietsenRelatief_20': 48}, {'ID': 10, 'RegioS': 'LD01  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 1306028, 'TotaalMotorvoertuigen_2': 1132392, 'TotaalPersonenautoS_3': 909302, 'PersonenautoSRelatief_4': 522, 'InBezitNatuurlijkePersonen_5': 849120, 'InBezitNatuurlijkePersonenRelatief_6': 487, 'TotaalBedrijfsvoertuigen_7': 311913, 'TotaalBedrijfsmotorvoertuigen_8': 138277, 'TotaalAanhangwagensEnOpleggers_9': 173636, 'TotaalBedrijfsmotorvoertuigen_10': 138277, 'Bestelauto_11': 114632, 'VrachtautoExclTrekkerVoorOplegger_12': 6032, 'TrekkerVoorOplegger_13': 7841, 'SpeciaalVoertuig_14': 8018, 'Bus_15': 1754, 'TotaalAanhangwagensEnOpleggers_16': 173636, 'Aanhangwagen_17': 161460, 'Oplegger_18': 12176, 'TotaalMotorfietsen_19': 84813, 'MotorfietsenRelatief_20': 49}, {'ID': 11, 'RegioS': 'LD01  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 1323830, 'TotaalMotorvoertuigen_2': 1146105, 'TotaalPersonenautoS_3': 918843, 'PersonenautoSRelatief_4': 523, 'InBezitNatuurlijkePersonen_5': 854929, 'InBezitNatuurlijkePersonenRelatief_6': 486, 'TotaalBedrijfsvoertuigen_7': 318031, 'TotaalBedrijfsmotorvoertuigen_8': 140306, 'TotaalAanhangwagensEnOpleggers_9': 177725, 'TotaalBedrijfsmotorvoertuigen_10': 140306, 'Bestelauto_11': 116242, 'VrachtautoExclTrekkerVoorOplegger_12': 6115, 'TrekkerVoorOplegger_13': 8217, 'SpeciaalVoertuig_14': 7962, 'Bus_15': 1770, 'TotaalAanhangwagensEnOpleggers_16': 177725, 'Aanhangwagen_17': 164967, 'Oplegger_18': 12758, 'TotaalMotorfietsen_19': 86956, 'MotorfietsenRelatief_20': 49}, {'ID': 12, 'RegioS': 'LD01  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 1348457, 'TotaalMotorvoertuigen_2': 1167559, 'TotaalPersonenautoS_3': 935286, 'PersonenautoSRelatief_4': 529, 'InBezitNatuurlijkePersonen_5': 868136, 'InBezitNatuurlijkePersonenRelatief_6': 491, 'TotaalBedrijfsvoertuigen_7': 324217, 'TotaalBedrijfsmotorvoertuigen_8': 143319, 'TotaalAanhangwagensEnOpleggers_9': 180898, 'TotaalBedrijfsmotorvoertuigen_10': 143319, 'Bestelauto_11': 118773, 'VrachtautoExclTrekkerVoorOplegger_12': 6210, 'TrekkerVoorOplegger_13': 8465, 'SpeciaalVoertuig_14': 7973, 'Bus_15': 1898, 'TotaalAanhangwagensEnOpleggers_16': 180898, 'Aanhangwagen_17': 167549, 'Oplegger_18': 13349, 'TotaalMotorfietsen_19': 88954, 'MotorfietsenRelatief_20': 50}, {'ID': 13, 'RegioS': 'LD01  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 1382691, 'TotaalMotorvoertuigen_2': 1197613, 'TotaalPersonenautoS_3': 956702, 'PersonenautoSRelatief_4': 539, 'InBezitNatuurlijkePersonen_5': 887989, 'InBezitNatuurlijkePersonenRelatief_6': 501, 'TotaalBedrijfsvoertuigen_7': 334463, 'TotaalBedrijfsmotorvoertuigen_8': 149385, 'TotaalAanhangwagensEnOpleggers_9': 185078, 'TotaalBedrijfsmotorvoertuigen_10': 149385, 'Bestelauto_11': 124515, 'VrachtautoExclTrekkerVoorOplegger_12': 6346, 'TrekkerVoorOplegger_13': 8682, 'SpeciaalVoertuig_14': 7839, 'Bus_15': 2003, 'TotaalAanhangwagensEnOpleggers_16': 185078, 'Aanhangwagen_17': 171492, 'Oplegger_18': 13586, 'TotaalMotorfietsen_19': 91526, 'MotorfietsenRelatief_20': 52}, {'ID': 14, 'RegioS': 'LD02  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 2681905, 'TotaalMotorvoertuigen_2': 2379788, 'TotaalPersonenautoS_3': 1960967, 'PersonenautoSRelatief_4': 538, 'InBezitNatuurlijkePersonen_5': 1650345, 'InBezitNatuurlijkePersonenRelatief_6': 453, 'TotaalBedrijfsvoertuigen_7': 572987, 'TotaalBedrijfsmotorvoertuigen_8': 270870, 'TotaalAanhangwagensEnOpleggers_9': 302117, 'TotaalBedrijfsmotorvoertuigen_10': 270870, 'Bestelauto_11': 220181, 'VrachtautoExclTrekkerVoorOplegger_12': 15452, 'TrekkerVoorOplegger_13': 19915, 'SpeciaalVoertuig_14': 13685, 'Bus_15': 1637, 'TotaalAanhangwagensEnOpleggers_16': 302117, 'Aanhangwagen_17': 266932, 'Oplegger_18': 35185, 'TotaalMotorfietsen_19': 147951, 'MotorfietsenRelatief_20': 41}, {'ID': 15, 'RegioS': 'LD02  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 2726141, 'TotaalMotorvoertuigen_2': 2417677, 'TotaalPersonenautoS_3': 1993086, 'PersonenautoSRelatief_4': 543, 'InBezitNatuurlijkePersonen_5': 1675234, 'InBezitNatuurlijkePersonenRelatief_6': 456, 'TotaalBedrijfsvoertuigen_7': 583199, 'TotaalBedrijfsmotorvoertuigen_8': 274735, 'TotaalAanhangwagensEnOpleggers_9': 308464, 'TotaalBedrijfsmotorvoertuigen_10': 274735, 'Bestelauto_11': 223489, 'VrachtautoExclTrekkerVoorOplegger_12': 15535, 'TrekkerVoorOplegger_13': 20522, 'SpeciaalVoertuig_14': 13570, 'Bus_15': 1619, 'TotaalAanhangwagensEnOpleggers_16': 308464, 'Aanhangwagen_17': 271720, 'Oplegger_18': 36744, 'TotaalMotorfietsen_19': 149856, 'MotorfietsenRelatief_20': 41}, {'ID': 16, 'RegioS': 'LD02  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 2751825, 'TotaalMotorvoertuigen_2': 2439853, 'TotaalPersonenautoS_3': 2007195, 'PersonenautoSRelatief_4': 544, 'InBezitNatuurlijkePersonen_5': 1709869, 'InBezitNatuurlijkePersonenRelatief_6': 463, 'TotaalBedrijfsvoertuigen_7': 591553, 'TotaalBedrijfsmotorvoertuigen_8': 279581, 'TotaalAanhangwagensEnOpleggers_9': 311972, 'TotaalBedrijfsmotorvoertuigen_10': 279581, 'Bestelauto_11': 228626, 'VrachtautoExclTrekkerVoorOplegger_12': 15330, 'TrekkerVoorOplegger_13': 20554, 'SpeciaalVoertuig_14': 13405, 'Bus_15': 1666, 'TotaalAanhangwagensEnOpleggers_16': 311972, 'Aanhangwagen_17': 274090, 'Oplegger_18': 37882, 'TotaalMotorfietsen_19': 153077, 'MotorfietsenRelatief_20': 41}, {'ID': 17, 'RegioS': 'LD02  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 2798014, 'TotaalMotorvoertuigen_2': 2479477, 'TotaalPersonenautoS_3': 2036509, 'PersonenautoSRelatief_4': 548, 'InBezitNatuurlijkePersonen_5': 1742917, 'InBezitNatuurlijkePersonenRelatief_6': 469, 'TotaalBedrijfsvoertuigen_7': 605341, 'TotaalBedrijfsmotorvoertuigen_8': 286804, 'TotaalAanhangwagensEnOpleggers_9': 318537, 'TotaalBedrijfsmotorvoertuigen_10': 286804, 'Bestelauto_11': 235200, 'VrachtautoExclTrekkerVoorOplegger_12': 15372, 'TrekkerVoorOplegger_13': 21325, 'SpeciaalVoertuig_14': 13404, 'Bus_15': 1503, 'TotaalAanhangwagensEnOpleggers_16': 318537, 'Aanhangwagen_17': 280953, 'Oplegger_18': 37584, 'TotaalMotorfietsen_19': 156164, 'MotorfietsenRelatief_20': 42}, {'ID': 18, 'RegioS': 'LD02  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 2827322, 'TotaalMotorvoertuigen_2': 2502221, 'TotaalPersonenautoS_3': 2053063, 'PersonenautoSRelatief_4': 546, 'InBezitNatuurlijkePersonen_5': 1755265, 'InBezitNatuurlijkePersonenRelatief_6': 466, 'TotaalBedrijfsvoertuigen_7': 614763, 'TotaalBedrijfsmotorvoertuigen_8': 289662, 'TotaalAanhangwagensEnOpleggers_9': 325101, 'TotaalBedrijfsmotorvoertuigen_10': 289662, 'Bestelauto_11': 237536, 'VrachtautoExclTrekkerVoorOplegger_12': 15446, 'TrekkerVoorOplegger_13': 21966, 'SpeciaalVoertuig_14': 13389, 'Bus_15': 1325, 'TotaalAanhangwagensEnOpleggers_16': 325101, 'Aanhangwagen_17': 286448, 'Oplegger_18': 38653, 'TotaalMotorfietsen_19': 159496, 'MotorfietsenRelatief_20': 42}, {'ID': 19, 'RegioS': 'LD02  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 2886291, 'TotaalMotorvoertuigen_2': 2557678, 'TotaalPersonenautoS_3': 2099758, 'PersonenautoSRelatief_4': 554, 'InBezitNatuurlijkePersonen_5': 1784371, 'InBezitNatuurlijkePersonenRelatief_6': 471, 'TotaalBedrijfsvoertuigen_7': 623701, 'TotaalBedrijfsmotorvoertuigen_8': 295088, 'TotaalAanhangwagensEnOpleggers_9': 328613, 'TotaalBedrijfsmotorvoertuigen_10': 295088, 'Bestelauto_11': 243028, 'VrachtautoExclTrekkerVoorOplegger_12': 15553, 'TrekkerVoorOplegger_13': 21908, 'SpeciaalVoertuig_14': 13427, 'Bus_15': 1172, 'TotaalAanhangwagensEnOpleggers_16': 328613, 'Aanhangwagen_17': 289266, 'Oplegger_18': 39347, 'TotaalMotorfietsen_19': 162832, 'MotorfietsenRelatief_20': 43}, {'ID': 20, 'RegioS': 'LD02  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 2996180, 'TotaalMotorvoertuigen_2': 2660938, 'TotaalPersonenautoS_3': 2178717, 'PersonenautoSRelatief_4': 571, 'InBezitNatuurlijkePersonen_5': 1826667, 'InBezitNatuurlijkePersonenRelatief_6': 479, 'TotaalBedrijfsvoertuigen_7': 650332, 'TotaalBedrijfsmotorvoertuigen_8': 315090, 'TotaalAanhangwagensEnOpleggers_9': 335242, 'TotaalBedrijfsmotorvoertuigen_10': 315090, 'Bestelauto_11': 262354, 'VrachtautoExclTrekkerVoorOplegger_12': 15962, 'TrekkerVoorOplegger_13': 22227, 'SpeciaalVoertuig_14': 13370, 'Bus_15': 1177, 'TotaalAanhangwagensEnOpleggers_16': 335242, 'Aanhangwagen_17': 295385, 'Oplegger_18': 39857, 'TotaalMotorfietsen_19': 167131, 'MotorfietsenRelatief_20': 44}, {'ID': 21, 'RegioS': 'LD03  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 4811592, 'TotaalMotorvoertuigen_2': 4395686, 'TotaalPersonenautoS_3': 3664768, 'PersonenautoSRelatief_4': 444, 'InBezitNatuurlijkePersonen_5': 3226511, 'InBezitNatuurlijkePersonenRelatief_6': 391, 'TotaalBedrijfsvoertuigen_7': 873969, 'TotaalBedrijfsmotorvoertuigen_8': 458063, 'TotaalAanhangwagensEnOpleggers_9': 415906, 'TotaalBedrijfsmotorvoertuigen_10': 458063, 'Bestelauto_11': 376944, 'VrachtautoExclTrekkerVoorOplegger_12': 24092, 'TrekkerVoorOplegger_13': 30181, 'SpeciaalVoertuig_14': 21580, 'Bus_15': 5266, 'TotaalAanhangwagensEnOpleggers_16': 415906, 'Aanhangwagen_17': 348570, 'Oplegger_18': 67336, 'TotaalMotorfietsen_19': 272855, 'MotorfietsenRelatief_20': 33}, {'ID': 22, 'RegioS': 'LD03  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 4896984, 'TotaalMotorvoertuigen_2': 4475788, 'TotaalPersonenautoS_3': 3728258, 'PersonenautoSRelatief_4': 448, 'InBezitNatuurlijkePersonen_5': 3264412, 'InBezitNatuurlijkePersonenRelatief_6': 392, 'TotaalBedrijfsvoertuigen_7': 891671, 'TotaalBedrijfsmotorvoertuigen_8': 470475, 'TotaalAanhangwagensEnOpleggers_9': 421196, 'TotaalBedrijfsmotorvoertuigen_10': 470475, 'Bestelauto_11': 388986, 'VrachtautoExclTrekkerVoorOplegger_12': 24072, 'TrekkerVoorOplegger_13': 30726, 'SpeciaalVoertuig_14': 21324, 'Bus_15': 5367, 'TotaalAanhangwagensEnOpleggers_16': 421196, 'Aanhangwagen_17': 352413, 'Oplegger_18': 68783, 'TotaalMotorfietsen_19': 277055, 'MotorfietsenRelatief_20': 33}, {'ID': 23, 'RegioS': 'LD03  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 4957710, 'TotaalMotorvoertuigen_2': 4536614, 'TotaalPersonenautoS_3': 3780217, 'PersonenautoSRelatief_4': 452, 'InBezitNatuurlijkePersonen_5': 3323349, 'InBezitNatuurlijkePersonenRelatief_6': 397, 'TotaalBedrijfsvoertuigen_7': 895738, 'TotaalBedrijfsmotorvoertuigen_8': 474642, 'TotaalAanhangwagensEnOpleggers_9': 421096, 'TotaalBedrijfsmotorvoertuigen_10': 474642, 'Bestelauto_11': 394589, 'VrachtautoExclTrekkerVoorOplegger_12': 23610, 'TrekkerVoorOplegger_13': 30689, 'SpeciaalVoertuig_14': 21011, 'Bus_15': 4743, 'TotaalAanhangwagensEnOpleggers_16': 421096, 'Aanhangwagen_17': 351942, 'Oplegger_18': 69154, 'TotaalMotorfietsen_19': 281755, 'MotorfietsenRelatief_20': 34}, {'ID': 24, 'RegioS': 'LD03  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 5053249, 'TotaalMotorvoertuigen_2': 4621605, 'TotaalPersonenautoS_3': 3848599, 'PersonenautoSRelatief_4': 457, 'InBezitNatuurlijkePersonen_5': 3371983, 'InBezitNatuurlijkePersonenRelatief_6': 400, 'TotaalBedrijfsvoertuigen_7': 919426, 'TotaalBedrijfsmotorvoertuigen_8': 487782, 'TotaalAanhangwagensEnOpleggers_9': 431644, 'TotaalBedrijfsmotorvoertuigen_10': 487782, 'Bestelauto_11': 407179, 'VrachtautoExclTrekkerVoorOplegger_12': 23467, 'TrekkerVoorOplegger_13': 31697, 'SpeciaalVoertuig_14': 20949, 'Bus_15': 4490, 'TotaalAanhangwagensEnOpleggers_16': 431644, 'Aanhangwagen_17': 357130, 'Oplegger_18': 74514, 'TotaalMotorfietsen_19': 285224, 'MotorfietsenRelatief_20': 34}, {'ID': 25, 'RegioS': 'LD03  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 5116505, 'TotaalMotorvoertuigen_2': 4676564, 'TotaalPersonenautoS_3': 3890006, 'PersonenautoSRelatief_4': 456, 'InBezitNatuurlijkePersonen_5': 3384174, 'InBezitNatuurlijkePersonenRelatief_6': 396, 'TotaalBedrijfsvoertuigen_7': 937089, 'TotaalBedrijfsmotorvoertuigen_8': 497148, 'TotaalAanhangwagensEnOpleggers_9': 439941, 'TotaalBedrijfsmotorvoertuigen_10': 497148, 'Bestelauto_11': 414825, 'VrachtautoExclTrekkerVoorOplegger_12': 23393, 'TrekkerVoorOplegger_13': 33203, 'SpeciaalVoertuig_14': 20914, 'Bus_15': 4813, 'TotaalAanhangwagensEnOpleggers_16': 439941, 'Aanhangwagen_17': 361541, 'Oplegger_18': 78400, 'TotaalMotorfietsen_19': 289410, 'MotorfietsenRelatief_20': 34}, {'ID': 26, 'RegioS': 'LD03  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 5185552, 'TotaalMotorvoertuigen_2': 4744501, 'TotaalPersonenautoS_3': 3947927, 'PersonenautoSRelatief_4': 459, 'InBezitNatuurlijkeP

In [15]:
#this will print the typed dataset in json format, so name value pairs
url = "https://opendata.cbs.nl/ODataApi/odata/85235NED/TypedDataSet"
posts = requests.get(url).json()

print (posts)
print("test")

{'odata.metadata': 'https://opendata.cbs.nl/ODataApi/OData/85235NED/$metadata#Cbs.OData.WebAPI.TypedDataSet', 'value': [{'ID': 0, 'RegioS': 'NL01  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 11372065, 'TotaalMotorvoertuigen_2': 10199679, 'TotaalPersonenautoS_3': 8442982, 'PersonenautoSRelatief_4': 489, 'InBezitNatuurlijkePersonen_5': 7452085, 'InBezitNatuurlijkePersonenRelatief_6': 431, 'TotaalBedrijfsvoertuigen_7': 2283037, 'TotaalBedrijfsmotorvoertuigen_8': 1110651, 'TotaalAanhangwagensEnOpleggers_9': 1172386, 'TotaalBedrijfsmotorvoertuigen_10': 1110651, 'Bestelauto_11': 903005, 'VrachtautoExclTrekkerVoorOplegger_12': 61652, 'TrekkerVoorOplegger_13': 78788, 'SpeciaalVoertuig_14': 57693, 'Bus_15': 9513, 'TotaalAanhangwagensEnOpleggers_16': 1172386, 'Aanhangwagen_17': 1008412, 'Oplegger_18': 163974, 'TotaalMotorfietsen_19': 646046, 'MotorfietsenRelatief_20': 37}, {'ID': 1, 'RegioS': 'NL01  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 11567203, 'TotaalMotorvoertuigen_2': 10374721, 'TotaalPersonenautoS_3': 8584391, 'PersonenautoSRelatief_4': 493, 'InBezitNatuurlijkePersonen_5': 7548770, 'InBezitNatuurlijkePersonenRelatief_6': 434, 'TotaalBedrijfsvoertuigen_7': 2328425, 'TotaalBedrijfsmotorvoertuigen_8': 1135943, 'TotaalAanhangwagensEnOpleggers_9': 1192482, 'TotaalBedrijfsmotorvoertuigen_10': 1135943, 'Bestelauto_11': 927251, 'VrachtautoExclTrekkerVoorOplegger_12': 61746, 'TrekkerVoorOplegger_13': 80118, 'SpeciaalVoertuig_14': 57129, 'Bus_15': 9699, 'TotaalAanhangwagensEnOpleggers_16': 1192482, 'Aanhangwagen_17': 1023980, 'Oplegger_18': 168502, 'TotaalMotorfietsen_19': 654387, 'MotorfietsenRelatief_20': 38}, {'ID': 2, 'RegioS': 'NL01  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 11704406, 'TotaalMotorvoertuigen_2': 10504756, 'TotaalPersonenautoS_3': 8686419, 'PersonenautoSRelatief_4': 497, 'InBezitNatuurlijkePersonen_5': 7683236, 'InBezitNatuurlijkePersonenRelatief_6': 440, 'TotaalBedrijfsvoertuigen_7': 2351390, 'TotaalBedrijfsmotorvoertuigen_8': 1151740, 'TotaalAanhangwagensEnOpleggers_9': 1199650, 'TotaalBedrijfsmotorvoertuigen_10': 1151740, 'Bestelauto_11': 945433, 'VrachtautoExclTrekkerVoorOplegger_12': 60831, 'TrekkerVoorOplegger_13': 79932, 'SpeciaalVoertuig_14': 56494, 'Bus_15': 9050, 'TotaalAanhangwagensEnOpleggers_16': 1199650, 'Aanhangwagen_17': 1029636, 'Oplegger_18': 170014, 'TotaalMotorfietsen_19': 666597, 'MotorfietsenRelatief_20': 38}, {'ID': 3, 'RegioS': 'NL01  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 11917133, 'TotaalMotorvoertuigen_2': 10688353, 'TotaalPersonenautoS_3': 8827709, 'PersonenautoSRelatief_4': 502, 'InBezitNatuurlijkePersonen_5': 7803950, 'InBezitNatuurlijkePersonenRelatief_6': 444, 'TotaalBedrijfsvoertuigen_7': 2411637, 'TotaalBedrijfsmotorvoertuigen_8': 1182857, 'TotaalAanhangwagensEnOpleggers_9': 1228780, 'TotaalBedrijfsmotorvoertuigen_10': 1182857, 'Bestelauto_11': 974792, 'VrachtautoExclTrekkerVoorOplegger_12': 60867, 'TrekkerVoorOplegger_13': 82436, 'SpeciaalVoertuig_14': 56230, 'Bus_15': 8532, 'TotaalAanhangwagensEnOpleggers_16': 1228780, 'Aanhangwagen_17': 1051486, 'Oplegger_18': 177294, 'TotaalMotorfietsen_19': 677787, 'MotorfietsenRelatief_20': 39}, {'ID': 4, 'RegioS': 'NL01  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 12063981, 'TotaalMotorvoertuigen_2': 10808892, 'TotaalPersonenautoS_3': 8917107, 'PersonenautoSRelatief_4': 501, 'InBezitNatuurlijkePersonen_5': 7842473, 'InBezitNatuurlijkePersonenRelatief_6': 440, 'TotaalBedrijfsvoertuigen_7': 2456150, 'TotaalBedrijfsmotorvoertuigen_8': 1201061, 'TotaalAanhangwagensEnOpleggers_9': 1255089, 'TotaalBedrijfsmotorvoertuigen_10': 1201061, 'Bestelauto_11': 989841, 'VrachtautoExclTrekkerVoorOplegger_12': 60811, 'TrekkerVoorOplegger_13': 85679, 'SpeciaalVoertuig_14': 55974, 'Bus_15': 8756, 'TotaalAanhangwagensEnOpleggers_16': 1255089, 'Aanhangwagen_17': 1069827, 'Oplegger_18': 185262, 'TotaalMotorfietsen_19': 690724, 'MotorfietsenRelatief_20': 39}, {'ID': 5, 'RegioS': 'NL01  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 12255576, 'TotaalMotorvoertuigen_2': 10989401, 'TotaalPersonenautoS_3': 9067393, 'PersonenautoSRelatief_4': 505, 'InBezitNatuurlijkePersonen_5': 7946287, 'InBezitNatuurlijkePersonenRelatief_6': 443, 'TotaalBedrijfsvoertuigen_7': 2484868, 'TotaalBedrijfsmotorvoertuigen_8': 1218693, 'TotaalAanhangwagensEnOpleggers_9': 1266175, 'TotaalBedrijfsmotorvoertuigen_10': 1218693, 'Bestelauto_11': 1006477, 'VrachtautoExclTrekkerVoorOplegger_12': 61521, 'TrekkerVoorOplegger_13': 86457, 'SpeciaalVoertuig_14': 55563, 'Bus_15': 8675, 'TotaalAanhangwagensEnOpleggers_16': 1266175, 'Aanhangwagen_17': 1077996, 'Oplegger_18': 188179, 'TotaalMotorfietsen_19': 703315, 'MotorfietsenRelatief_20': 39}, {'ID': 6, 'RegioS': 'NL01  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 12519332, 'TotaalMotorvoertuigen_2': 11234293, 'TotaalPersonenautoS_3': 9247810, 'PersonenautoSRelatief_4': 513, 'InBezitNatuurlijkePersonen_5': 8112145, 'InBezitNatuurlijkePersonenRelatief_6': 450, 'TotaalBedrijfsvoertuigen_7': 2550931, 'TotaalBedrijfsmotorvoertuigen_8': 1265892, 'TotaalAanhangwagensEnOpleggers_9': 1285039, 'TotaalBedrijfsmotorvoertuigen_10': 1265892, 'Bestelauto_11': 1050688, 'VrachtautoExclTrekkerVoorOplegger_12': 63197, 'TrekkerVoorOplegger_13': 87837, 'SpeciaalVoertuig_14': 54937, 'Bus_15': 9233, 'TotaalAanhangwagensEnOpleggers_16': 1285039, 'Aanhangwagen_17': 1096141, 'Oplegger_18': 188898, 'TotaalMotorfietsen_19': 720591, 'MotorfietsenRelatief_20': 40}, {'ID': 7, 'RegioS': 'LD01  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 1235405, 'TotaalMotorvoertuigen_2': 1071110, 'TotaalPersonenautoS_3': 861974, 'PersonenautoSRelatief_4': 500, 'InBezitNatuurlijkePersonen_5': 807624, 'InBezitNatuurlijkePersonenRelatief_6': 469, 'TotaalBedrijfsvoertuigen_7': 292901, 'TotaalBedrijfsmotorvoertuigen_8': 128606, 'TotaalAanhangwagensEnOpleggers_9': 164295, 'TotaalBedrijfsmotorvoertuigen_10': 128606, 'Bestelauto_11': 105174, 'VrachtautoExclTrekkerVoorOplegger_12': 5998, 'TrekkerVoorOplegger_13': 7520, 'SpeciaalVoertuig_14': 8205, 'Bus_15': 1709, 'TotaalAanhangwagensEnOpleggers_16': 164295, 'Aanhangwagen_17': 153306, 'Oplegger_18': 10989, 'TotaalMotorfietsen_19': 80530, 'MotorfietsenRelatief_20': 47}, {'ID': 8, 'RegioS': 'LD01  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 1258055, 'TotaalMotorvoertuigen_2': 1090809, 'TotaalPersonenautoS_3': 877666, 'PersonenautoSRelatief_4': 507, 'InBezitNatuurlijkePersonen_5': 819862, 'InBezitNatuurlijkePersonenRelatief_6': 474, 'TotaalBedrijfsvoertuigen_7': 299030, 'TotaalBedrijfsmotorvoertuigen_8': 131784, 'TotaalAanhangwagensEnOpleggers_9': 167246, 'TotaalBedrijfsmotorvoertuigen_10': 131784, 'Bestelauto_11': 108085, 'VrachtautoExclTrekkerVoorOplegger_12': 6062, 'TrekkerVoorOplegger_13': 7640, 'SpeciaalVoertuig_14': 8170, 'Bus_15': 1827, 'TotaalAanhangwagensEnOpleggers_16': 167246, 'Aanhangwagen_17': 155921, 'Oplegger_18': 11325, 'TotaalMotorfietsen_19': 81359, 'MotorfietsenRelatief_20': 47}, {'ID': 9, 'RegioS': 'LD01  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 1279895, 'TotaalMotorvoertuigen_2': 1110551, 'TotaalPersonenautoS_3': 892790, 'PersonenautoSRelatief_4': 515, 'InBezitNatuurlijkePersonen_5': 834668, 'InBezitNatuurlijkePersonenRelatief_6': 482, 'TotaalBedrijfsvoertuigen_7': 304021, 'TotaalBedrijfsmotorvoertuigen_8': 134677, 'TotaalAanhangwagensEnOpleggers_9': 169344, 'TotaalBedrijfsmotorvoertuigen_10': 134677, 'Bestelauto_11': 111159, 'VrachtautoExclTrekkerVoorOplegger_12': 5961, 'TrekkerVoorOplegger_13': 7640, 'SpeciaalVoertuig_14': 8118, 'Bus_15': 1799, 'TotaalAanhangwagensEnOpleggers_16': 169344, 'Aanhangwagen_17': 157735, 'Oplegger_18': 11609, 'TotaalMotorfietsen_19': 83084, 'MotorfietsenRelatief_20': 48}, {'ID': 10, 'RegioS': 'LD01  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 1306028, 'TotaalMotorvoertuigen_2': 1132392, 'TotaalPersonenautoS_3': 909302, 'PersonenautoSRelatief_4': 522, 'InBezitNatuurlijkePersonen_5': 849120, 'InBezitNatuurlijkePersonenRelatief_6': 487, 'TotaalBedrijfsvoertuigen_7': 311913, 'TotaalBedrijfsmotorvoertuigen_8': 138277, 'TotaalAanhangwagensEnOpleggers_9': 173636, 'TotaalBedrijfsmotorvoertuigen_10': 138277, 'Bestelauto_11': 114632, 'VrachtautoExclTrekkerVoorOplegger_12': 6032, 'TrekkerVoorOplegger_13': 7841, 'SpeciaalVoertuig_14': 8018, 'Bus_15': 1754, 'TotaalAanhangwagensEnOpleggers_16': 173636, 'Aanhangwagen_17': 161460, 'Oplegger_18': 12176, 'TotaalMotorfietsen_19': 84813, 'MotorfietsenRelatief_20': 49}, {'ID': 11, 'RegioS': 'LD01  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 1323830, 'TotaalMotorvoertuigen_2': 1146105, 'TotaalPersonenautoS_3': 918843, 'PersonenautoSRelatief_4': 523, 'InBezitNatuurlijkePersonen_5': 854929, 'InBezitNatuurlijkePersonenRelatief_6': 486, 'TotaalBedrijfsvoertuigen_7': 318031, 'TotaalBedrijfsmotorvoertuigen_8': 140306, 'TotaalAanhangwagensEnOpleggers_9': 177725, 'TotaalBedrijfsmotorvoertuigen_10': 140306, 'Bestelauto_11': 116242, 'VrachtautoExclTrekkerVoorOplegger_12': 6115, 'TrekkerVoorOplegger_13': 8217, 'SpeciaalVoertuig_14': 7962, 'Bus_15': 1770, 'TotaalAanhangwagensEnOpleggers_16': 177725, 'Aanhangwagen_17': 164967, 'Oplegger_18': 12758, 'TotaalMotorfietsen_19': 86956, 'MotorfietsenRelatief_20': 49}, {'ID': 12, 'RegioS': 'LD01  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 1348457, 'TotaalMotorvoertuigen_2': 1167559, 'TotaalPersonenautoS_3': 935286, 'PersonenautoSRelatief_4': 529, 'InBezitNatuurlijkePersonen_5': 868136, 'InBezitNatuurlijkePersonenRelatief_6': 491, 'TotaalBedrijfsvoertuigen_7': 324217, 'TotaalBedrijfsmotorvoertuigen_8': 143319, 'TotaalAanhangwagensEnOpleggers_9': 180898, 'TotaalBedrijfsmotorvoertuigen_10': 143319, 'Bestelauto_11': 118773, 'VrachtautoExclTrekkerVoorOplegger_12': 6210, 'TrekkerVoorOplegger_13': 8465, 'SpeciaalVoertuig_14': 7973, 'Bus_15': 1898, 'TotaalAanhangwagensEnOpleggers_16': 180898, 'Aanhangwagen_17': 167549, 'Oplegger_18': 13349, 'TotaalMotorfietsen_19': 88954, 'MotorfietsenRelatief_20': 50}, {'ID': 13, 'RegioS': 'LD01  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 1382691, 'TotaalMotorvoertuigen_2': 1197613, 'TotaalPersonenautoS_3': 956702, 'PersonenautoSRelatief_4': 539, 'InBezitNatuurlijkePersonen_5': 887989, 'InBezitNatuurlijkePersonenRelatief_6': 501, 'TotaalBedrijfsvoertuigen_7': 334463, 'TotaalBedrijfsmotorvoertuigen_8': 149385, 'TotaalAanhangwagensEnOpleggers_9': 185078, 'TotaalBedrijfsmotorvoertuigen_10': 149385, 'Bestelauto_11': 124515, 'VrachtautoExclTrekkerVoorOplegger_12': 6346, 'TrekkerVoorOplegger_13': 8682, 'SpeciaalVoertuig_14': 7839, 'Bus_15': 2003, 'TotaalAanhangwagensEnOpleggers_16': 185078, 'Aanhangwagen_17': 171492, 'Oplegger_18': 13586, 'TotaalMotorfietsen_19': 91526, 'MotorfietsenRelatief_20': 52}, {'ID': 14, 'RegioS': 'LD02  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 2681905, 'TotaalMotorvoertuigen_2': 2379788, 'TotaalPersonenautoS_3': 1960967, 'PersonenautoSRelatief_4': 538, 'InBezitNatuurlijkePersonen_5': 1650345, 'InBezitNatuurlijkePersonenRelatief_6': 453, 'TotaalBedrijfsvoertuigen_7': 572987, 'TotaalBedrijfsmotorvoertuigen_8': 270870, 'TotaalAanhangwagensEnOpleggers_9': 302117, 'TotaalBedrijfsmotorvoertuigen_10': 270870, 'Bestelauto_11': 220181, 'VrachtautoExclTrekkerVoorOplegger_12': 15452, 'TrekkerVoorOplegger_13': 19915, 'SpeciaalVoertuig_14': 13685, 'Bus_15': 1637, 'TotaalAanhangwagensEnOpleggers_16': 302117, 'Aanhangwagen_17': 266932, 'Oplegger_18': 35185, 'TotaalMotorfietsen_19': 147951, 'MotorfietsenRelatief_20': 41}, {'ID': 15, 'RegioS': 'LD02  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 2726141, 'TotaalMotorvoertuigen_2': 2417677, 'TotaalPersonenautoS_3': 1993086, 'PersonenautoSRelatief_4': 543, 'InBezitNatuurlijkePersonen_5': 1675234, 'InBezitNatuurlijkePersonenRelatief_6': 456, 'TotaalBedrijfsvoertuigen_7': 583199, 'TotaalBedrijfsmotorvoertuigen_8': 274735, 'TotaalAanhangwagensEnOpleggers_9': 308464, 'TotaalBedrijfsmotorvoertuigen_10': 274735, 'Bestelauto_11': 223489, 'VrachtautoExclTrekkerVoorOplegger_12': 15535, 'TrekkerVoorOplegger_13': 20522, 'SpeciaalVoertuig_14': 13570, 'Bus_15': 1619, 'TotaalAanhangwagensEnOpleggers_16': 308464, 'Aanhangwagen_17': 271720, 'Oplegger_18': 36744, 'TotaalMotorfietsen_19': 149856, 'MotorfietsenRelatief_20': 41}, {'ID': 16, 'RegioS': 'LD02  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 2751825, 'TotaalMotorvoertuigen_2': 2439853, 'TotaalPersonenautoS_3': 2007195, 'PersonenautoSRelatief_4': 544, 'InBezitNatuurlijkePersonen_5': 1709869, 'InBezitNatuurlijkePersonenRelatief_6': 463, 'TotaalBedrijfsvoertuigen_7': 591553, 'TotaalBedrijfsmotorvoertuigen_8': 279581, 'TotaalAanhangwagensEnOpleggers_9': 311972, 'TotaalBedrijfsmotorvoertuigen_10': 279581, 'Bestelauto_11': 228626, 'VrachtautoExclTrekkerVoorOplegger_12': 15330, 'TrekkerVoorOplegger_13': 20554, 'SpeciaalVoertuig_14': 13405, 'Bus_15': 1666, 'TotaalAanhangwagensEnOpleggers_16': 311972, 'Aanhangwagen_17': 274090, 'Oplegger_18': 37882, 'TotaalMotorfietsen_19': 153077, 'MotorfietsenRelatief_20': 41}, {'ID': 17, 'RegioS': 'LD02  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 2798014, 'TotaalMotorvoertuigen_2': 2479477, 'TotaalPersonenautoS_3': 2036509, 'PersonenautoSRelatief_4': 548, 'InBezitNatuurlijkePersonen_5': 1742917, 'InBezitNatuurlijkePersonenRelatief_6': 469, 'TotaalBedrijfsvoertuigen_7': 605341, 'TotaalBedrijfsmotorvoertuigen_8': 286804, 'TotaalAanhangwagensEnOpleggers_9': 318537, 'TotaalBedrijfsmotorvoertuigen_10': 286804, 'Bestelauto_11': 235200, 'VrachtautoExclTrekkerVoorOplegger_12': 15372, 'TrekkerVoorOplegger_13': 21325, 'SpeciaalVoertuig_14': 13404, 'Bus_15': 1503, 'TotaalAanhangwagensEnOpleggers_16': 318537, 'Aanhangwagen_17': 280953, 'Oplegger_18': 37584, 'TotaalMotorfietsen_19': 156164, 'MotorfietsenRelatief_20': 42}, {'ID': 18, 'RegioS': 'LD02  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 2827322, 'TotaalMotorvoertuigen_2': 2502221, 'TotaalPersonenautoS_3': 2053063, 'PersonenautoSRelatief_4': 546, 'InBezitNatuurlijkePersonen_5': 1755265, 'InBezitNatuurlijkePersonenRelatief_6': 466, 'TotaalBedrijfsvoertuigen_7': 614763, 'TotaalBedrijfsmotorvoertuigen_8': 289662, 'TotaalAanhangwagensEnOpleggers_9': 325101, 'TotaalBedrijfsmotorvoertuigen_10': 289662, 'Bestelauto_11': 237536, 'VrachtautoExclTrekkerVoorOplegger_12': 15446, 'TrekkerVoorOplegger_13': 21966, 'SpeciaalVoertuig_14': 13389, 'Bus_15': 1325, 'TotaalAanhangwagensEnOpleggers_16': 325101, 'Aanhangwagen_17': 286448, 'Oplegger_18': 38653, 'TotaalMotorfietsen_19': 159496, 'MotorfietsenRelatief_20': 42}, {'ID': 19, 'RegioS': 'LD02  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 2886291, 'TotaalMotorvoertuigen_2': 2557678, 'TotaalPersonenautoS_3': 2099758, 'PersonenautoSRelatief_4': 554, 'InBezitNatuurlijkePersonen_5': 1784371, 'InBezitNatuurlijkePersonenRelatief_6': 471, 'TotaalBedrijfsvoertuigen_7': 623701, 'TotaalBedrijfsmotorvoertuigen_8': 295088, 'TotaalAanhangwagensEnOpleggers_9': 328613, 'TotaalBedrijfsmotorvoertuigen_10': 295088, 'Bestelauto_11': 243028, 'VrachtautoExclTrekkerVoorOplegger_12': 15553, 'TrekkerVoorOplegger_13': 21908, 'SpeciaalVoertuig_14': 13427, 'Bus_15': 1172, 'TotaalAanhangwagensEnOpleggers_16': 328613, 'Aanhangwagen_17': 289266, 'Oplegger_18': 39347, 'TotaalMotorfietsen_19': 162832, 'MotorfietsenRelatief_20': 43}, {'ID': 20, 'RegioS': 'LD02  ', 'Perioden': '2025JJ00', 'TotaalWegvoertuigen_1': 2996180, 'TotaalMotorvoertuigen_2': 2660938, 'TotaalPersonenautoS_3': 2178717, 'PersonenautoSRelatief_4': 571, 'InBezitNatuurlijkePersonen_5': 1826667, 'InBezitNatuurlijkePersonenRelatief_6': 479, 'TotaalBedrijfsvoertuigen_7': 650332, 'TotaalBedrijfsmotorvoertuigen_8': 315090, 'TotaalAanhangwagensEnOpleggers_9': 335242, 'TotaalBedrijfsmotorvoertuigen_10': 315090, 'Bestelauto_11': 262354, 'VrachtautoExclTrekkerVoorOplegger_12': 15962, 'TrekkerVoorOplegger_13': 22227, 'SpeciaalVoertuig_14': 13370, 'Bus_15': 1177, 'TotaalAanhangwagensEnOpleggers_16': 335242, 'Aanhangwagen_17': 295385, 'Oplegger_18': 39857, 'TotaalMotorfietsen_19': 167131, 'MotorfietsenRelatief_20': 44}, {'ID': 21, 'RegioS': 'LD03  ', 'Perioden': '2019JJ00', 'TotaalWegvoertuigen_1': 4811592, 'TotaalMotorvoertuigen_2': 4395686, 'TotaalPersonenautoS_3': 3664768, 'PersonenautoSRelatief_4': 444, 'InBezitNatuurlijkePersonen_5': 3226511, 'InBezitNatuurlijkePersonenRelatief_6': 391, 'TotaalBedrijfsvoertuigen_7': 873969, 'TotaalBedrijfsmotorvoertuigen_8': 458063, 'TotaalAanhangwagensEnOpleggers_9': 415906, 'TotaalBedrijfsmotorvoertuigen_10': 458063, 'Bestelauto_11': 376944, 'VrachtautoExclTrekkerVoorOplegger_12': 24092, 'TrekkerVoorOplegger_13': 30181, 'SpeciaalVoertuig_14': 21580, 'Bus_15': 5266, 'TotaalAanhangwagensEnOpleggers_16': 415906, 'Aanhangwagen_17': 348570, 'Oplegger_18': 67336, 'TotaalMotorfietsen_19': 272855, 'MotorfietsenRelatief_20': 33}, {'ID': 22, 'RegioS': 'LD03  ', 'Perioden': '2020JJ00', 'TotaalWegvoertuigen_1': 4896984, 'TotaalMotorvoertuigen_2': 4475788, 'TotaalPersonenautoS_3': 3728258, 'PersonenautoSRelatief_4': 448, 'InBezitNatuurlijkePersonen_5': 3264412, 'InBezitNatuurlijkePersonenRelatief_6': 392, 'TotaalBedrijfsvoertuigen_7': 891671, 'TotaalBedrijfsmotorvoertuigen_8': 470475, 'TotaalAanhangwagensEnOpleggers_9': 421196, 'TotaalBedrijfsmotorvoertuigen_10': 470475, 'Bestelauto_11': 388986, 'VrachtautoExclTrekkerVoorOplegger_12': 24072, 'TrekkerVoorOplegger_13': 30726, 'SpeciaalVoertuig_14': 21324, 'Bus_15': 5367, 'TotaalAanhangwagensEnOpleggers_16': 421196, 'Aanhangwagen_17': 352413, 'Oplegger_18': 68783, 'TotaalMotorfietsen_19': 277055, 'MotorfietsenRelatief_20': 33}, {'ID': 23, 'RegioS': 'LD03  ', 'Perioden': '2021JJ00', 'TotaalWegvoertuigen_1': 4957710, 'TotaalMotorvoertuigen_2': 4536614, 'TotaalPersonenautoS_3': 3780217, 'PersonenautoSRelatief_4': 452, 'InBezitNatuurlijkePersonen_5': 3323349, 'InBezitNatuurlijkePersonenRelatief_6': 397, 'TotaalBedrijfsvoertuigen_7': 895738, 'TotaalBedrijfsmotorvoertuigen_8': 474642, 'TotaalAanhangwagensEnOpleggers_9': 421096, 'TotaalBedrijfsmotorvoertuigen_10': 474642, 'Bestelauto_11': 394589, 'VrachtautoExclTrekkerVoorOplegger_12': 23610, 'TrekkerVoorOplegger_13': 30689, 'SpeciaalVoertuig_14': 21011, 'Bus_15': 4743, 'TotaalAanhangwagensEnOpleggers_16': 421096, 'Aanhangwagen_17': 351942, 'Oplegger_18': 69154, 'TotaalMotorfietsen_19': 281755, 'MotorfietsenRelatief_20': 34}, {'ID': 24, 'RegioS': 'LD03  ', 'Perioden': '2022JJ00', 'TotaalWegvoertuigen_1': 5053249, 'TotaalMotorvoertuigen_2': 4621605, 'TotaalPersonenautoS_3': 3848599, 'PersonenautoSRelatief_4': 457, 'InBezitNatuurlijkePersonen_5': 3371983, 'InBezitNatuurlijkePersonenRelatief_6': 400, 'TotaalBedrijfsvoertuigen_7': 919426, 'TotaalBedrijfsmotorvoertuigen_8': 487782, 'TotaalAanhangwagensEnOpleggers_9': 431644, 'TotaalBedrijfsmotorvoertuigen_10': 487782, 'Bestelauto_11': 407179, 'VrachtautoExclTrekkerVoorOplegger_12': 23467, 'TrekkerVoorOplegger_13': 31697, 'SpeciaalVoertuig_14': 20949, 'Bus_15': 4490, 'TotaalAanhangwagensEnOpleggers_16': 431644, 'Aanhangwagen_17': 357130, 'Oplegger_18': 74514, 'TotaalMotorfietsen_19': 285224, 'MotorfietsenRelatief_20': 34}, {'ID': 25, 'RegioS': 'LD03  ', 'Perioden': '2023JJ00', 'TotaalWegvoertuigen_1': 5116505, 'TotaalMotorvoertuigen_2': 4676564, 'TotaalPersonenautoS_3': 3890006, 'PersonenautoSRelatief_4': 456, 'InBezitNatuurlijkePersonen_5': 3384174, 'InBezitNatuurlijkePersonenRelatief_6': 396, 'TotaalBedrijfsvoertuigen_7': 937089, 'TotaalBedrijfsmotorvoertuigen_8': 497148, 'TotaalAanhangwagensEnOpleggers_9': 439941, 'TotaalBedrijfsmotorvoertuigen_10': 497148, 'Bestelauto_11': 414825, 'VrachtautoExclTrekkerVoorOplegger_12': 23393, 'TrekkerVoorOplegger_13': 33203, 'SpeciaalVoertuig_14': 20914, 'Bus_15': 4813, 'TotaalAanhangwagensEnOpleggers_16': 439941, 'Aanhangwagen_17': 361541, 'Oplegger_18': 78400, 'TotaalMotorfietsen_19': 289410, 'MotorfietsenRelatief_20': 34}, {'ID': 26, 'RegioS': 'LD03  ', 'Perioden': '2024JJ00', 'TotaalWegvoertuigen_1': 5185552, 'TotaalMotorvoertuigen_2': 4744501, 'TotaalPersonenautoS_3': 3947927, 'PersonenautoSRelatief_4': 459, 'InBezitNatuurlijkeP

In [16]:
# select columns by first selecting the "value" key from json format
# then specify the specific columns
dfposts = pd.DataFrame(posts["value"])[['Aanhangwagen_17',
            'Bestelauto_11',
            'Bus_15',
            'ID',
            'InBezitNatuurlijkePersonenRelatief_6',
            'InBezitNatuurlijkePersonen_5',
            'MotorfietsenRelatief_20',
            'Oplegger_18',
            'Perioden',
            'PersonenautoSRelatief_4',
            'RegioS',
            'SpeciaalVoertuig_14',
            'TotaalAanhangwagensEnOpleggers_16',
            'TotaalAanhangwagensEnOpleggers_9',
            'TotaalBedrijfsmotorvoertuigen_10',
            'TotaalBedrijfsmotorvoertuigen_8',
            'TotaalBedrijfsvoertuigen_7',
            'TotaalMotorfietsen_19',
            'TotaalMotorvoertuigen_2',
            'TotaalPersonenautoS_3',
            'TotaalWegvoertuigen_1',
            'TrekkerVoorOplegger_13',
            'VrachtautoExclTrekkerVoorOplegger_12']]
dfposts.head()

,Aanhangwagen_17,Bestelauto_11,Bus_15,ID,InBezitNatuurlijkePersonenRelatief_6,InBezitNatuurlijkePersonen_5,MotorfietsenRelatief_20,Oplegger_18,Perioden,PersonenautoSRelatief_4,...,TotaalAanhangwagensEnOpleggers_9,TotaalBedrijfsmotorvoertuigen_10,TotaalBedrijfsmotorvoertuigen_8,TotaalBedrijfsvoertuigen_7,TotaalMotorfietsen_19,TotaalMotorvoertuigen_2,TotaalPersonenautoS_3,TotaalWegvoertuigen_1,TrekkerVoorOplegger_13,VrachtautoExclTrekkerVoorOplegger_12
0,1008412,903005,9513,0,431,7452085,37,163974,2019JJ00,489,...,1172386,1110651,1110651,2283037,646046,10199679,8442982,11372065,78788,61652
1,1023980,927251,9699,1,434,7548770,38,168502,2020JJ00,493,...,1192482,1135943,1135943,2328425,654387,10374721,8584391,11567203,80118,61746
2,1029636,945433,9050,2,440,7683236,38,170014,2021JJ00,497,...,1199650,1151740,1151740,2351390,666597,10504756,8686419,11704406,79932,60831
3,1051486,974792,8532,3,444,7803950,39,177294,2022JJ00,502,...,1228780,1182857,1182857,2411637,677787,10688353,8827709,11917133,82436,60867
4,1069827,989841,8756,4,440,7842473,39,185262,2023JJ00,501,...,1255089,1201061,1201061,2456150,690724,10808892,8917107,12063981,85679,60811

In [17]:
columns_vehicledb = ['Aanhangwagen_17',
            'Bestelauto_11',
            'Bus_15',
            'InBezitNatuurlijkePersonenRelatief_6',
            'InBezitNatuurlijkePersonen_5',
            'MotorfietsenRelatief_20',
            'Oplegger_18',
            'PersonenautoSRelatief_4',
            'SpeciaalVoertuig_14',
            'TotaalAanhangwagensEnOpleggers_16',
            'TotaalAanhangwagensEnOpleggers_9',
            'TotaalBedrijfsmotorvoertuigen_10',
            'TotaalBedrijfsmotorvoertuigen_8',
            'TotaalBedrijfsvoertuigen_7',
            'TotaalMotorfietsen_19',
            'TotaalMotorvoertuigen_2',
            'TotaalPersonenautoS_3',
            'TotaalWegvoertuigen_1',
            'TrekkerVoorOplegger_13',
            'VrachtautoExclTrekkerVoorOplegger_12']

In [18]:
dfprovince = dfposts[dfposts["RegioS"].str.startswith("PV")]
print(dfprovince)

     Aanhangwagen_17  Bestelauto_11  Bus_15   ID  \
35             44354          31359      99   35
36             45012          32179     291   36
37             45677          33225     343   37
38             46662          34112     346   38
39             47653          34680     372   39
..               ...            ...     ...  ...
114            70317          52209     351  114
115            72178          53705     332  115
116            74049          54396     361  116
117            74725          55128     362  117
118            75962          56734     352  118

     InBezitNatuurlijkePersonenRelatief_6  InBezitNatuurlijkePersonen_5  \
35                                    431                        251789
36                                    436                        255316
37                                    444                        260707
38                                    450                        265561
39                                    448                        267111
..                                    ...                           ...
114                                   509                        567638
115                                   513                        573817
116                                   510                        575540
117                                   513                        581050
118                                   520                        590239

     MotorfietsenRelatief_20  Oplegger_18  Perioden  PersonenautoSRelatief_4  \
35                        43         2984  2019JJ00                      471
36                        43         3089  2020JJ00                      477
37                        44         3114  2021JJ00                      484
38                        45         3218  2022JJ00                      491
39                        45         3349  2023JJ00                      491
..                       ...          ...       ...                      ...
114                       41        16683  2021JJ00                      531
115                       42        17497  2022JJ00                      536
116                       43        18419  2023JJ00                      534
117                       43        19140  2024JJ00                      537
118                       44        19491  2025JJ00                      545

     ... TotaalAanhangwagensEnOpleggers_9  TotaalBedrijfsmotorvoertuigen_10  \
35   ...                            47338                             37610
36   ...                            48101                             38656
37   ...                            48791                             39761
38   ...                            49880                             40693
39   ...                            51002                             41382
..   ...                              ...                               ...
114  ...                            87000                             66018
115  ...                            89675                             67585
116  ...                            92468                             68298
117  ...                            93865                             68830
118  ...                            95453                             70311

     TotaalBedrijfsmotorvoertuigen_8  TotaalBedrijfsvoertuigen_7  \
35                             37610                       84948
36                             38656                       86757
37                             39761                       88552
38                             40693                       90573
39                             41382                       92384
..                               ...                         ...
114                            66018                      153018
115                            67585                      157260
116                            68298                      160766
117                            68830                      162695
118                            70311                      165764

     TotaalMotorfietsen_19  TotaalMotorvoertuigen_2  TotaalPersonenautoS_3  \
35                   24861                   337248                 274777
36                   25055                   342992                 279281
37                   25665                   349476                 284050
38                   26277                   356506                 289536
39                   26977                   360941                 292582
..                     ...                      ...                    ...
114                  46140                   705201                 593043
115                  46906                   714292                 599801
116                  48135                   719023                 602590
117                  48942                   726790                 609018
118                  49894                   738834                 618629

     TotaalWegvoertuigen_1  TrekkerVoorOplegger_13  \
35                  384586                    1940
36                  391093                    1970
37                  398267                    1977
38                  406386                    2008
39                  411943                    2105
..                     ...                     ...
114                 792201                    5446
115                 803967                    5602
116                 811491                    5655
117                 820655                    5503
118                 834287                    5382

     VrachtautoExclTrekkerVoorOplegger_12
35                                   1588
36                                   1582
37                                   1591
38                                   1611
39                                   1660
..                                    ...
114                                  3972
115                                  3906
116                                  3872
117                                  3875
118                                  3922

[84 rows x 23 columns]

In [19]:
columns_vehicledb = ['Aanhangwagen_17',
            'Bestelauto_11',
            'Bus_15',
            'InBezitNatuurlijkePersonenRelatief_6',
            'InBezitNatuurlijkePersonen_5',
            'MotorfietsenRelatief_20',
            'Oplegger_18',
            'PersonenautoSRelatief_4',
            'SpeciaalVoertuig_14',
            'TotaalAanhangwagensEnOpleggers_16',
            'TotaalAanhangwagensEnOpleggers_9',
            'TotaalBedrijfsmotorvoertuigen_10',
            'TotaalBedrijfsmotorvoertuigen_8',
            'TotaalBedrijfsvoertuigen_7',
            'TotaalMotorfietsen_19',
            'TotaalMotorvoertuigen_2',
            'TotaalPersonenautoS_3',
            'TotaalWegvoertuigen_1',
            'TrekkerVoorOplegger_13',
            'VrachtautoExclTrekkerVoorOplegger_12']
# encode the data in order to link them to the right province (for visualization)
pvencoding = {'PV20':'Groningen',
              'PV21':'Friesland',
              'PV22':'Drenthe',
              'PV23':'Overijssel',
              'PV24':'Flevoland',
              'PV25':'Gelderland',
              'PV26':'Utrecht',
              'PV27':'Noord-Holland',
              'PV28':'Zuid-Holland',
              'PV29':'Zeeland',
              'PV30':'Noord-Brabant',
              'PV31':'Limburg'}


dfprovince = dfprovince.groupby('RegioS')[columns_vehicledb].sum().reset_index() # group the regios together and calculate the sum from columns_vehicledb per regio
dfprovince["Sum"] = dfprovince[columns_vehicledb].sum(axis=1) #calculate for each row the sum
dfprovince['RegioS'] = dfprovince['RegioS'].astype(str).str.strip()
dfprovince['RegioS'] = dfprovince['RegioS'].map(pvencoding) #transform the initial station_numbers using the pvencoding by implementing the map funtion
df_vehicles = dfprovince[["RegioS","Sum"]].copy()
print(df_vehicles)

           RegioS       Sum
0       Groningen  11936457
1       Friesland  14990976
2         Drenthe  11755668
3      Overijssel  25136738
4       Flevoland  12550586
5      Gelderland  43979534
6         Utrecht  27202822
7   Noord-Holland  47438165
8    Zuid-Holland  62190626
9         Zeeland   8732228
10  Noord-Brabant  57201144
11        Limburg  23560147

In [20]:
print(df_vehicles['Sum'].skew())

0.7002018218075269

In [21]:
df_vehicles['Sum_log'] = np.log(df_vehicles['Sum'])
print(df_vehicles['Sum_log'])
print(df_vehicles['Sum_log'].skew())

0     16.295108
1     16.522959
2     16.279846
3     17.039841
4     16.345278
5     17.599235
6     17.118831
7     17.674938
8     17.945715
9     15.982531
10    17.862084
11    16.975067
Name: Sum_log, dtype: float64
0.10440535907135731

In [22]:
# Standardize the values for number of vehicles
standardization = df_vehicles[['Sum_log']]

standardize = StandardScaler().fit_transform(standardization)

df_vehicles_standardized = df_vehicles.copy()
df_vehicles_standardized['Sum_st'] = pd.DataFrame(standardize, columns=standardization.columns)

print(df_vehicles_standardized)

           RegioS       Sum    Sum_log    Sum_st
0       Groningen  11936457  16.295108 -1.028907
1       Friesland  14990976  16.522959 -0.681598
2         Drenthe  11755668  16.279846 -1.052171
3      Overijssel  25136738  17.039841  0.106275
4       Flevoland  12550586  16.345278 -0.952434
5      Gelderland  43979534  17.599235  0.958949
6         Utrecht  27202822  17.118831  0.226679
7   Noord-Holland  47438165  17.674938  1.074341
8    Zuid-Holland  62190626  17.945715  1.487082
9         Zeeland   8732228  15.982531 -1.505362
10  Noord-Brabant  57201144  17.862084  1.359605
11        Limburg  23560147  16.975067  0.007542

In [23]:
# Assign the vehicles values to the df
def get_vehicles(row):
    province = row['Province']
    match = df_vehicles_standardized[df_vehicles_standardized['RegioS'] == province]
    return match['Sum_st'].iloc[0] if not match.empty else 0

if 'vehicles_tot' not in df_values.columns:
    df_values['vehicles_tot'] = 0

df_values['vehicles_tot'] = df_values.apply(get_vehicles, axis=1)

In [24]:
display(df_values)

,Year_Month,Province,Average NO2 Value,Average PM2.5 Value,Average PM10 Value,area_km2_st,vehicles_tot
0,1990-01-01,Drenthe,1.324917,NaN,NaN,0.000000,-1.052171
1,1990-01-01,Flevoland,1.764091,NaN,NaN,0.000000,-0.952434
2,1990-01-01,Friesland,1.215124,NaN,NaN,0.000000,-0.681598
3,1990-01-01,Gelderland,2.422852,NaN,NaN,0.000000,0.958949
4,1990-01-01,Groningen,1.215124,NaN,NaN,0.000000,-1.028907
...,...,...,...,...,...,...,...
1435,2024-12-01,Noord-Holland,0.336776,0.122001,-0.208369,2.276287,1.074341
1436,2024-12-01,Overijssel,-0.870952,-0.956227,-1.362410,0.000000,0.106275
1437,2024-12-01,Utrecht,-0.102398,0.391558,-0.669985,0.137367,0.226679
1438,2024-12-01,Zeeland,-0.761158,NaN,-0.208369,0.000000,-1.505362
1439,2024-12-01,Zuid-Holland,0.336776,0.391558,0.022440,0.976009,1.487082

In [25]:
# Save the df as a csv file
df_values.to_csv('df_values.csv')